### ISSUE TITLE
How did you pick the color palette/scheme?

### ISSUE THREAD

**Issue by CarlsonCarlson** [whatyouhide/vim-gotham#58]
I love this color scheme so much! I'm really curious, how did you pick the color palette/scheme? What should one do if they wanted to make their own color palette/scheme? How should one start?

**Comment by whatyouhide** [comment]
It's been years, but at the time I'm pretty sure I used the [Spectrum app](http://www.eigenlogik.com/spectrum/mac) and just played with colors until I found something I liked. I tried to have colors that made sense for accent colors, errors, and stuff like that, since I was designing this with a programming color scheme use case in mind. Hopefully that answers your question! Other than that, play with colors and see what you like :) I originally made this for me but then other people liked it. I recommend designing for your taste so at least you'll be happy with it :)
